"""Cut Lucy's voice into phrases, offline, once.

The source is a single 17-second recording of a ferret playing (Freesound 155115 by
J. Zazvurek, CC BY 4.0). Inside it are 82 separate calls: mostly 30-60ms dook syllables,
with a loud excited run near the end.

Picking a random offset into that file at runtime would cut a call in half roughly half
the time. So we do the analysis here instead, on a machine with time to spare, and ship
the boundaries. At runtime the game only rolls dice against a list — the same
pre-generate-then-select-with-math shape the rest of the studio runs on.

A phrase, not a syllable, is the playable unit: ferrets dook in runs, and one 40ms chirp
on its own sounds like a glitch.

    python scripts/ferret-slices.py > src/voice-slices.ts
"""
import wave, array, sys

SRC = "src/lucy-voice.wav"
RES = 0.005          # envelope resolution, seconds
GAP_PHRASE = 0.220   # a silence longer than this ends a phrase
MAX_LEN = 1.400      # anything longer gets split at its widest internal gap
MIN_LEN = 0.120      # anything shorter is a click, not a noise


def envelope(a, peak, sr):
    w = int(sr * RES)
    out = []
    for i in range(0, len(a) - w, w):
        m = 0
        for v in a[i:i + w]:
            av = v if v >= 0 else -v
            if av > m: m = av
        out.append(m / peak)
    return out


def calls(env):
    """Individual vocalisations, with hysteresis so one call is not split by its own dips."""
    floor = sorted(env)[int(len(env) * 0.25)]
    hi, lo = max(floor * 7, 0.035), max(floor * 3, 0.015)
    segs, on, st = [], False, 0
    for i, e in enumerate(env):
        if not on and e > hi: on, st = True, i
        elif on and e < lo: on = False; segs.append((st, i))
    if on: segs.append((st, len(env)))
    merged = []
    for s, e in segs:
        if merged and s - merged[-1][1] < 12: merged[-1] = (merged[-1][0], e)
        else: merged.append((s, e))
    return [(s, e) for s, e in merged if e - s >= 6]


def split_long(group):
    """Recursively halve an over-long phrase at its widest internal silence."""
    s, e = group[0][0], group[-1][1]
    if (e - s) * RES <= MAX_LEN or len(group) < 4:
        return [group]
    widest, at = -1, None
    for i in range(1, len(group)):
        g = group[i][0] - group[i - 1][1]
        if g > widest: widest, at = g, i
    if at is None: return [group]
    return split_long(group[:at]) + split_long(group[at:])


def main():
    w = wave.open(SRC, "rb")
    sr, n = w.getframerate(), w.getnframes()
    a = array.array("h", w.readframes(n))
    peak = max(max(a), -min(a))
    env = envelope(a, peak, sr)

    groups, cs = [], calls(env)
    for s, e in cs:
        if groups and (s - groups[-1][-1][1]) * RES <= GAP_PHRASE: groups[-1].append((s, e))
        else: groups.append([(s, e)])

    phrases = []
    for g in groups:
        for part in split_long(g):
            s, e = part[0][0], part[-1][1]
            if (e - s) * RES < MIN_LEN: continue
            phrases.append({
                "at": round(s * RES, 3),
                "len": round((e - s) * RES, 3),
                "calls": len(part),
                "peak": round(max(max(env[x:y]) for x, y in part), 3),
            })

    # Tiers are how the game asks for a noise. Loudness is the ferret's own volume in
    # the recording, which tracks how worked up she was — exactly the axis the sim wants.
    def tier(p):
        if p["peak"] >= 0.45: return "loud"
        if p["peak"] >= 0.28: return "mid"
        return "soft"

    for p in phrases: p["tier"] = tier(p)

    out = sys.stdout
    out.write('/* GENERATED by scripts/ferret-slices.py — do not edit by hand.\n\n')
    out.write("   Lucy's voice, cut into whole phrases. Source: Freesound 155115, \"Ferret\"\n")
    out.write("   by J. Zazvurek, CC BY 4.0 — credited in-game, see PRE-ADS.md.\n\n")
    out.write("   `at` and `len` are seconds into the recording. `tier` is how loud she was,\n")
    out.write("   which is the closest thing the tape has to a mood. */\n")
    out.write("export type Slice = { at: number; len: number; calls: number; peak: number; tier: \"soft\" | \"mid\" | \"loud\" };\n\n")
    out.write("export const SLICES: Slice[] = [\n")
    for p in phrases:
        out.write('  { at: %.3f, len: %.3f, calls: %d, peak: %.3f, tier: "%s" },\n'
                  % (p["at"], p["len"], p["calls"], p["peak"], p["tier"]))
    out.write("];\n")
    n_by = {}
    for p in phrases: n_by[p["tier"]] = n_by.get(p["tier"], 0) + 1
    sys.stderr.write("%d phrases: %s\n" % (len(phrases), n_by))


main()
