/* GENERATED by scripts/ferret-slices.py — do not edit by hand.

   Lucy's voice, cut into whole phrases. Source: Freesound 155115, "Ferret"
   by J. Zazvurek, CC BY 4.0 — credited in-game, see PRE-ADS.md.

   `at` and `len` are seconds into the recording. `tier` is how loud she was,
   which is the closest thing the tape has to a mood. */
export type Slice = { at: number; len: number; calls: number; peak: number; tier: "soft" | "mid" | "loud" };

export const SLICES: Slice[] = [
  { at: 0.330, len: 0.250, calls: 3, peak: 0.377, tier: "mid" },
  { at: 1.030, len: 0.775, calls: 5, peak: 0.260, tier: "soft" },
  { at: 2.335, len: 1.195, calls: 8, peak: 0.349, tier: "mid" },
  { at: 3.755, len: 0.545, calls: 4, peak: 0.290, tier: "mid" },
  { at: 4.675, len: 0.585, calls: 5, peak: 0.334, tier: "mid" },
  { at: 5.595, len: 0.155, calls: 2, peak: 0.262, tier: "soft" },
  { at: 6.070, len: 0.775, calls: 6, peak: 0.295, tier: "mid" },
  { at: 7.110, len: 0.480, calls: 3, peak: 0.248, tier: "soft" },
  { at: 8.010, len: 0.350, calls: 3, peak: 0.332, tier: "mid" },
  { at: 8.690, len: 0.900, calls: 4, peak: 0.463, tier: "loud" },
  { at: 9.675, len: 1.150, calls: 9, peak: 0.562, tier: "loud" },
  { at: 11.870, len: 0.495, calls: 5, peak: 0.173, tier: "soft" },
  { at: 12.560, len: 0.335, calls: 3, peak: 0.265, tier: "soft" },
  { at: 12.995, len: 1.250, calls: 10, peak: 0.567, tier: "loud" },
  { at: 14.340, len: 0.150, calls: 2, peak: 0.528, tier: "loud" },
  { at: 14.605, len: 0.795, calls: 6, peak: 1.000, tier: "loud" },
  { at: 16.370, len: 0.265, calls: 2, peak: 0.233, tier: "soft" },
];
